### ISSUE TITLE
Could not load NIB in bundle: 'NSBundle  (loaded)' with name 'RMessageView'

### ISSUE THREAD

**Issue by martin072** [donileo/RMessage#62]
Hi,

I recently updated an app that uses RMessage (which I am using for long time), however, some apps crash with the following message:

`Could not load NIB in bundle: 'NSBundle  (loaded)' with name 'RMessageView'` 

Using it in iOS 13.3 on an iPad.

Any ideas?

**Comment by isadon** [comment]
Will look into this today. Hopefully its something I can reproduce.

**Comment by martin072** [comment]
Well, I can't reproduce it as I have 2 different iPads (one iPad mini and one iPad Air), and on both of them it works fine, it's very occasional I get feedback with this error, so I don't really get it. I am using Pod's in my project, so I should have the latest version..

**Comment by isadon** [comment]
@martin072 Can you pull develop and tell me if it fixes anything, even though I'm not expecting it to. Something I forgot to ask is what version of RMessage are you using? Based on your error message it seems your are using the 2.3.x version. There isn't any nib named RMessageView in the 3.x.x Swift version.

**Comment by martin072** [comment]
@donileo, the app is in a production state, pulling a developer version and releasing it would be a bit risky for me, further more it seems to be some isolated issues only, not at all reproducible.. 
I am using Pods, this was the output of the latest build:

 RMessage (2.3.2):
    - HexColors (~> 4.0)
    - PPTopMostController

(my project is in Objective C) 

Hope this helps

**Comment by gadgetboyme** [comment]
Hello,
I've come across this issue too.
I'm able to reproduce the issue when turning off mobile data and wifi. 
It occurs when I call:
[ErrorMessage showConnectionError:self.navigationController
                         errorMessage:errorMessage
                            errorCode:errorCode
                        refreshMethod:]
It falls over in RMessageView.m, Line 269:
self = [[NSBundle bundleForClass:[self class]] loadNibNamed:NSStringFromClass([self class]) owner:self options:nil].firstObject;

Using on iPhone XR running iOS 13.3.
Hope it helps.
Thanks

**Comment by isadon** [comment]
Made some changes that I believe fix these issues. Commit for the change is 91188050b443ea6d0550d7cd008a57e2830c87a8. Please pull `2.x.x_develop` and test. If all seems ok I will go ahead and put out a 2.3.3 release. I haven't tested if these issues affect the 3.x.x series but will test that a bit later.

If you have issues testing these changes since I have not actually put out a new `2.3.3` Pod release please pull `2.x.x_develop`, copy the RMessage Folder from it to your project and then use `pod 'RMessage', :path => '<path to copied RMessage folder>'` in your `Podfile` instead of what you have now to test the changes.

**Comment by isadon** [comment]
Just released a new version (2.3.3) via Pod; easier to test the fix now.

**Comment by tylerwilson** [comment]
I just did a pod update and it went to version 2.3.3. and when I ran I got the following crash:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not read RMessage config file from main bundle with name RMessageDefaultDesign.json'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e3cc88 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258b8bd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   RMessage                            0x000000010a48503e +[RMessageView setupGlobalDesignDictionary] + 494
	5   RMessage                            0x000000010a4853ab +[RMessageView addDesignsFromFileWithName:inBundle:] + 107
	6   RMessage                            0x000000010a4841b5 +[RMessage addDesignsFromFileWithName:inBundle:] + 101
	7   Salonbiz Book                       0x0000000104caa057 -[HomeViewController viewDidLoad] + 263

```
as seen I am calling the following method for it to read my custom RMessageDesigns.json:

`[RMessage addDesignsFromFileWithName:@"RMessageDesigns" inBundle:NSBundle.mainBundle];`

Thought you should know. I reverted to 2.3.2 and working again.BTW, I would love to use the 3.x series, but this app still has to support iOS 9.x. Hey, I don't like it either. :-(

**Comment by donileo** [comment]
If it was easier for me to test 2.3.2 this would be easier to fix. Unfortunately latest Xcode doesn't support build for iOS 7 which is the target 2.3.x series supports. Downgrading Xcode to something like Xcode 9 which does support 2.3.x requires me to run on something lower than catalina which I don't have a spare machine to do that with.

**Comment by isadon** [comment]
Can you please clean your build directory and your derived data and see if this happens?. I am not seeing that error message when building with latest Xcode on my end.

`RMessageDefaultDesign.json` is now part of RMessage's bundle which is one of the code changes that was committed. Given your error implies its not part of RMessage's bundle tells me your build is probably dirty somehow..

**Comment by tylerwilson** [comment]
Okay, cleaning did not work. But I did debug the code, and one issue is here: in 2.3.3 a static RMessageBundle property was added, but the init code fails to locate it properly. It fails on this line:

`  NSURL *resourceBundleURL = [appBundle URLForResource:@"RMessage" withExtension:@"bundle"];`

which then cause the lookup for the default json file to fail and then crash when trying to read.

in 2.3.2 it used a simple [NSBundle [self class]] which appears to work fine. I can debug further if you like, but for now i will be using 2.3.2.

**Comment by tylerwilson** [comment]
Side question: what would be the possibility of lowering the iOS version requirement of RMessage 3.0 down to iOS 9.3? Are there iOS 11 specific features it is using?

**Comment by isadon** [comment]
Lowering the requirement after its been declared for the 3.0 series isn't going to happen. That would be breaking the contract as far as what has already been declared for that release. The real issue is fixing this problem which is tedious on my end because I can't reproduce. On my end it works correctly on the latest Xcode 11 and iOS 13.5 runtime. I tried downgrading to Xcode 9/iOS 7.0 runtime isn't supported by Mac OS Catalina and I don't have a separate machine to run that on. I'll see if I can somehow run on iOS 9 runtime and see if I can catch the issue you are seeing.

Update: Yea, it seems Catalina dropped support for iOS 9 simulators. If someone other than @tylerwilson can somehow test on iOS 9 and iOS 7 and report back if this issue exists for them, it would be helpful at least in knowing if the issue is reproducible. If it is I'll still have to come up with a way to reproduce it myself somehow.

**Comment by tylerwilson** [comment]
FYI, I am running with Xcode 11.5 on an iPad 13.5 simulator. So not an issue with iOS 9..

**Comment by isadon** [comment]
Ok, can you try the RMessage demo target and see if you get the crash there? Just run the demo and hit a couple of buttons and see if they show. If this issue is specific to integrating RMessage via a Pod then maybe that’s where I can reproduce.

**Comment by isadon** [comment]
Ok, so just tested on a brand new Xcode 11.1 project with iPhone SE2 simulator, brought in RMessage 2.3.3 using Cocoapods. Using a RMessageDesigns.json file in my main app bundle via `[RMessage addDesignsFromFileWithName:@"RMessageDesigns" inBundle:NSBundle.mainBundle];`. Works perfectly on my end.

**Comment by tylerwilson** [comment]
Just to be sure, you included:

`use_frameworks!`

in your Podfile?

I narrowed it down to this line: 

`NSBundle *appBundle = [NSBundle mainBundle];`

which returns my main .app and so the next URLForResource will fail, since the resource is not a child. If I instead change that line to:

`NSBundle *appBundle = [NSBundle bundleForClass:[self class]];`

then everything works as expected. Thanks!

**Comment by isadon** [comment]
Ahh. That’s definitely the problem. Please see https://github.com/CocoaPods/CocoaPods/issues/3226. Its weird that for me even without making any change and doing use_frameworks! it still works.

**Comment by tylerwilson** [comment]
Great. Look forward to it. :-)

**Comment by isadon** [comment]
@tylerwilson Ok can you point your RMessage pod to 2.x.x_develop branch now and retest? Make sure to clean your build directories if possible. Also, what actual XCode version are you using to build your app?

**Comment by tylerwilson** [comment]
Okay, I updated my Podfile to:

`pod 'RMessage', :git => 'https://github.com/donileo/RMessage.git', :branch => '2.x.x_develop'`

updated, ran and all good! Thank you!

**Comment by isadon** [comment]
@tylerwilson Thanks for the bug report. Will put out a 2.3.4 release sometime soon today or tommorrow hopefully.

**Comment by isadon** [comment]
2.3.4 Release is now on Cocoapods.

**Comment by tylerwilson** [comment]
Verified that all is working for me now with 2.3.4. Thank you!

**Comment by isadon** [comment]
Closing this issue out as I believe it is fixed.

**Comment by martin072** [comment]
Hi, I still see the errors  with 2.3.4.. Many app crashes with the following debug info:

```
Could not load NIB in bundle: 'NSBundle  (not yet loaded)' with name 'RMessageView'
-or-
Could not load NIB in bundle: 'NSBundle  (loaded)' with name 'fwX-4r-u7q-view-Y9P-0D-SwC' and directory 'Main.storyboardc'
```

**Comment by isadon** [comment]
@martin072 What iOS version are you testing with?

**Comment by martin072** [comment]
I am receiving crash reports from various users. All of them are iOS 14.x with the most recent report for iOS 14.3 
I don’t know if it helps, but my project is in Objective C

**Comment by isadon** [comment]
Can you reproduce the crashes yourself if you run on a fresh project with iOS14?

**Comment by martin072** [comment]
No, that is the issue. It works fine on all my tests and devices. It’s just that some users report the app crashes. Totally random. I am not able to reproduce it.
